<Project Sdk="Aspire.AppHost.Sdk/13.4.6">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>c5c0438f-bb02-4a15-8a5e-74dd13b50d61</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Docker" />
    <PackageReference Include="Aspire.Hosting.JavaScript" />
    <PackageReference Include="Aspire.Hosting.Kafka" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" />
    <PackageReference Include="Aspire.Hosting.Redis" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference
      Include="..\aspire\src\Cezn.Aspire.Hosting.KafkaConnect\Cezn.Aspire.Hosting.KafkaConnect.csproj"
      IsAspireProjectResource="false"
    />
    <ProjectReference
      Include="..\aspire\src\Cezn.Aspire.Hosting.RedpandaConsole\Cezn.Aspire.Hosting.RedpandaConsole.csproj"
      IsAspireProjectResource="false"
    />
    <ProjectReference
      Include="..\aspire\src\Cezn.Aspire.Hosting.SchemaRegistry\Cezn.Aspire.Hosting.SchemaRegistry.csproj"
      IsAspireProjectResource="false"
    />
    <ProjectReference
      Include="..\aspire\src\Cezn.Aspire.Hosting.Grate\Cezn.Aspire.Hosting.Grate.csproj"
      IsAspireProjectResource="false"
    />
    <ProjectReference
      Include="..\aspire\src\Cezn.Aspire.Hosting.SwaggerUI\Cezn.Aspire.Hosting.SwaggerUI.csproj"
      IsAspireProjectResource="false"
    />
    <ProjectReference
      Include="..\aspire\src\Cezn.Aspire.Hosting.Utils\Cezn.Aspire.Hosting.Utils.csproj"
      IsAspireProjectResource="false"
    />
    <ProjectReference
      Include="..\aspire\src\Cezn.Aspire.Hosting.Monitoring\Cezn.Aspire.Hosting.Monitoring.csproj"
      IsAspireProjectResource="false"
    />
    <ProjectReference Include="..\src\services\Auth\Auth.csproj" />
    <ProjectReference Include="..\src\services\BookmarksApi\BookmarksApi.csproj" />
    <ProjectReference Include="..\src\services\TagsBookmarksSubscriber\TagsBookmarksSubscriber.csproj" />
    <ProjectReference Include="..\src\services\Gateway\Gateway.csproj" />
    <ProjectReference Include="..\src\services\StaticAssets\StaticAssets.csproj" />
  </ItemGroup>
</Project>
