#!/bin/bash
#
# Kafka Connect connector creation script for 'bookmarks-outbox'
# Generated by Aspire AppHost during publish
#
# Usage:
#   ./create-all-connectors.sh          # Run all connectors
#   KAFKA_CONNECT_URL=http://localhost:8083 ./create-all-connectors.sh  # External URL
#   SCHEMA_REGISTRY_URL=http://localhost:8081 ./create-all-connectors.sh  # External Schema Registry
#

set -euo pipefail

# Kafka Connect URL - defaults to Docker Compose internal service
KAFKA_CONNECT_URL="${KAFKA_CONNECT_URL:-http://kafka-connect:8083}"

# Schema Registry URL - defaults to Docker Compose internal service
SCHEMA_REGISTRY_URL="${SCHEMA_REGISTRY_URL:-http://schema-registry:8081}"

echo "Creating connector 'bookmarks-outbox' against $KAFKA_CONNECT_URL ..."

# Wait for Kafka Connect to be ready
MAX_RETRIES=30
RETRY_COUNT=0
while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
    if curl -sf "$KAFKA_CONNECT_URL/connector-plugins" > /dev/null 2>&1; then
        echo "Kafka Connect is ready."
        break
    fi
    RETRY_COUNT=$((RETRY_COUNT + 1))
    echo "Waiting for Kafka Connect... (attempt $RETRY_COUNT/$MAX_RETRIES)"
    sleep 2
done

if [ $RETRY_COUNT -eq $MAX_RETRIES ]; then
    echo "ERROR: Kafka Connect did not become ready after $MAX_RETRIES attempts."
    exit 1
fi

# Connector configuration (template with placeholders resolved at runtime)
CONNECTOR_CONFIG_TEMPLATE='
{
  "connector.class": "io.debezium.connector.postgresql.PostgresConnector",
  "tasks.max": "1",
  "database.hostname": "pg",
  "database.port": "5432",
  "database.user": "postgres",
  "database.password": "__PG-PASSWORD__",
  "database.dbname": "bookmarksdb",
  "plugin.name": "pgoutput",
  "topic.prefix": "outbox",
  "slot.name": "outbox_slot",
  "publication.name": "outbox_publication",
  "publication.autocreate.mode": "filtered",
  "snapshot.mode": "initial",
  "heartbeat.interval.ms": "5000",
  "provide.transaction.metadata": "true",
  "tombstones.on.delete": "true",
  "key.converter": "io.confluent.connect.protobuf.ProtobufConverter",
  "value.converter": "io.debezium.converters.BinaryDataConverter",
  "table.include.list": "public.outbox",
  "key.converter.schema.registry.url": "__SCHEMA_REGISTRY_URL__",
  "value.converter.delegate.converter.type": "org.apache.kafka.connect.json.JsonConverter",
  "value.converter.delegate.converter.type.schemas.enable": "false",
  "transforms": "outbox",
  "transforms.outbox.type": "io.debezium.transforms.outbox.EventRouter",
  "transforms.outbox.table.field.event.key": "user_id",
  "transforms.outbox.table.fields.additional.placement": "type:header:type",
  "tracing.span.context.field": "tracingspancontext",
  "tracing.with.context.field.only": "false"
}
'

# Resolve placeholders with environment variables
CONNECTOR_CONFIG=$(echo "$CONNECTOR_CONFIG_TEMPLATE" | sed "s|__SCHEMA_REGISTRY_URL__|$SCHEMA_REGISTRY_URL|g")
# Resolve remaining __VAR_NAME__ placeholders from environment (e.g. __PG_PASSWORD__ -> $PG_PASSWORD)
CONNECTOR_CONFIG=$(echo "$CONNECTOR_CONFIG" | sed -E 's/__([A-Z_]+)__/${\1}/g')

# Create or update the connector
RESPONSE=$(curl -s -w "\n%{http_code}" -X PUT \
    -H "Content-Type: application/json" \
    -d "$CONNECTOR_CONFIG" \
    "$KAFKA_CONNECT_URL/connectors/bookmarks-outbox/config")

HTTP_CODE=$(echo "$RESPONSE" | tail -n1)
BODY=$(echo "$RESPONSE" | sed '$d')

if [ "$HTTP_CODE" -ge 200 ] && [ "$HTTP_CODE" -lt 300 ]; then
    echo "SUCCESS: Connector 'bookmarks-outbox' created/updated."
else
    echo "ERROR: Failed to create connector 'bookmarks-outbox'. HTTP $HTTP_CODE"
    echo "$BODY"
    exit 1
fi

echo "Connector 'bookmarks-outbox' is ready."
