#!/bin/bash
#
# Master script to create all Kafka Connect connectors
# Generated by Aspire AppHost during publish
#
# Usage:
#   ./create-all-connectors.sh
#   KAFKA_CONNECT_URL=http://localhost:8083 ./create-all-connectors.sh
#   SCHEMA_REGISTRY_URL=http://localhost:8081 ./create-all-connectors.sh
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "========================================"
echo "  Kafka Connect Connector Setup"
echo "========================================"
echo ""

echo "--- Processing connector: bookmarks-outbox ---"
if [ -f "$SCRIPT_DIR/bookmarks-outbox.sh" ]; then
    bash "$SCRIPT_DIR/bookmarks-outbox.sh"
    echo ""
else
    echo "WARNING: Script for 'bookmarks-outbox' not found, skipping."
fi

echo "========================================"
echo "  All connectors processed"
echo "========================================"
