services:
  grafana:
    profiles:
      - infra
    image: grafana/grafana:13.1.1
    container_name: grafana
    mem_limit: 2g
    ports:
      - "0.0.0.0:3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./provisioning:/etc/grafana/provisioning:ro
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_PASSWORD__CHANGEREQUIRED=false
    depends_on:
      - prometheus

volumes:
  grafana_data:
