services:
  schema-registry:
    profiles:
      - infra
    image: confluentinc/cp-schema-registry:7.6.1
    ports:
      - "0.0.0.0:8081:8081"
    environment:
      - SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS=PLAINTEXT://broker1:29092
      - SCHEMA_REGISTRY_HOST_NAME=localhost
      - SCHEMA_REGISTRY_LISTENERS=http://0.0.0.0:8081
      - SCHEMA_REGISTRY_DEBUG=false
      - SCHEMA_REGISTRY_KAFKASTORE_TOPIC_CONFIGS=cleanup.policy=compact
