-- Create aspnet_roles table
CREATE TABLE IF NOT EXISTS aspnet_roles (
    id VARCHAR(255) PRIMARY KEY,
    name VARCHAR(256),
    normalized_name VARCHAR(256),
    concurrency_stamp VARCHAR(255)
);

CREATE TABLE "aspnet_role_claims" (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    role_id text NOT NULL REFERENCES "aspnet_roles" (id) ON DELETE CASCADE,
    claim_type text,
    claim_value text
);

-- Create aspnet_users table
CREATE TABLE IF NOT EXISTS aspnet_users (
    id VARCHAR(255) PRIMARY KEY,
    user_name VARCHAR(256),
    normalized_user_name VARCHAR(256),
    email VARCHAR(256),
    normalized_email VARCHAR(256),
    email_confirmed BOOLEAN NOT NULL DEFAULT FALSE,
    password_hash TEXT,
    security_stamp VARCHAR(255),
    concurrency_stamp VARCHAR(255),
    phone_number VARCHAR(255),
    phone_number_confirmed BOOLEAN NOT NULL DEFAULT FALSE,
    two_factor_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    lockout_end TIMESTAMPTZ,
    lockout_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    access_failed_count INTEGER NOT NULL DEFAULT 0,
    authenticator_key TEXT
);

-- Create aspnet_user_claims table
CREATE TABLE IF NOT EXISTS aspnet_user_claims (
    id SERIAL PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL REFERENCES aspnet_users(id) ON DELETE CASCADE,
    claim_type TEXT,
    claim_value TEXT
);

-- Create aspnet_user_logins table
CREATE TABLE IF NOT EXISTS aspnet_user_logins (
    login_provider VARCHAR(255) NOT NULL,
    provider_key VARCHAR(255) NOT NULL,
    provider_display_name VARCHAR(255),
    user_id VARCHAR(255) NOT NULL REFERENCES aspnet_users(id) ON DELETE CASCADE,
    PRIMARY KEY (login_provider, provider_key)
);

-- Create aspnet_user_roles table
CREATE TABLE IF NOT EXISTS aspnet_user_roles (
    user_id VARCHAR(255) NOT NULL REFERENCES aspnet_users(id) ON DELETE CASCADE,
    role_id VARCHAR(255) NOT NULL REFERENCES aspnet_roles(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, role_id)
);

-- Create aspnet_user_passkeys table for storing user passkeys
CREATE TABLE IF NOT EXISTS aspnet_user_passkeys (
    credential_id BYTEA PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL REFERENCES aspnet_users(id) ON DELETE CASCADE,
    data JSONB NOT NULL
);

-- Create aspnet_user_recovery_codes table for storing two-factor recovery codes
CREATE TABLE IF NOT EXISTS aspnet_user_recovery_codes (
    id SERIAL PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL REFERENCES aspnet_users(id) ON DELETE CASCADE,
    code VARCHAR(255) NOT NULL UNIQUE,
    redeemed BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "aspnet_user_tokens" (
    user_id text NOT NULL REFERENCES "aspnet_users" (id) ON DELETE CASCADE,
    login_provider character varying(128) NOT NULL,
    name character varying(128) NOT NULL,
    value text,
    PRIMARY KEY (user_id, login_provider, name)
);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_aspnet_users_normalized_user_name ON aspnet_users(normalized_user_name);
CREATE INDEX IF NOT EXISTS idx_aspnet_users_normalized_email ON aspnet_users(normalized_email);
CREATE INDEX IF NOT EXISTS idx_aspnet_user_claims_user_id ON aspnet_user_claims(user_id);
CREATE INDEX IF NOT EXISTS idx_aspnet_user_logins_user_id ON aspnet_user_logins(user_id);
CREATE INDEX IF NOT EXISTS idx_aspnet_user_roles_user_id ON aspnet_user_roles(user_id);
CREATE INDEX IF NOT EXISTS idx_aspnet_user_roles_role_id ON aspnet_user_roles(role_id);
CREATE INDEX IF NOT EXISTS idx_aspnet_user_passkeys_user_id ON aspnet_user_passkeys(user_id);
CREATE INDEX IF NOT EXISTS idx_aspnet_roles_normalized_name ON aspnet_roles(normalized_name);
CREATE INDEX IF NOT EXISTS idx_aspnet_user_recovery_codes_user_id ON aspnet_user_recovery_codes(user_id);
CREATE INDEX IF NOT EXISTS idx_aspnet_user_recovery_codes_code ON aspnet_user_recovery_codes(code);
