services:
  mailhog:
    profiles:
      - infra
    image: mailhog/mailhog:v1.0.1
    ports:
      - "0.0.0.0:1025:1025" # SMTP
      - "0.0.0.0:8025:8025" # Web UI
    # depends_on:
    #   - otel-collector
    # logging: *logging
