services:
  console:
    profiles:
      - infra
    image: docker.redpanda.com/redpandadata/console:v3.0.1
    ports:
      - "0.0.0.0:8084:8080"
    restart: no
    entrypoint: /bin/sh
    command: -c "echo \"$$CONSOLE_CONFIG_FILE\" > /tmp/config.yml; /app/console"
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["broker1:29092"]
        schemaRegistry:
          enabled: true
          urls: ["http://schema-registry:8081"]
        kafkaConnect:
          enabled: true
          clusters:
            - name: datagen
              url: http://kafka-connect:8083
    depends_on:
      - broker1
      - schema-registry
