services:
  db:
    profiles:
      - infra
    image: postgres:16.2
    ports:
      - "0.0.0.0:5432:5432"
    environment:
      POSTGRES_PASSWORD: secret
      OTEL_SERVICE_NAME: "db"
    command:
      - postgres
      - -c
      - wal_level=logical
      - -c
      - max_wal_senders=10
      - -c
      - log_min_duration_statement=100
