receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - "*"
          allowed_headers:
            - "Content-Type"
          max_age: 7200
  fluentforward:
    endpoint: 0.0.0.0:8006

exporters:
  otlp:
    endpoint: aspire-dashboard:18889
    tls:
      insecure: true
  debug:
    verbosity: detailed
  elasticsearch:
    endpoints: ["http://elasticsearch:9200"]

processors:
  resource:
    attributes:
      # doesn't work for some reason
      - key: service.name
        from_attribute: com.docker.compose.service
        action: insert
  # remove attribute added by fluentd logging driver
  attributes:
    actions:
      - key: com.docker.compose.service
        action: delete

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      exporters: [otlp]
    logs:
      receivers: [otlp]
      exporters: [otlp]
    logs/fluentd:
      receivers: [fluentforward]
      processors: [resource, attributes]
      exporters: [otlp]
